import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "primary-fixed": "#dce1ff",
        "surface-bright": "#faf8ff",
        "surface-variant": "#e2e1ed",
        "on-secondary-fixed": "#0b1c30",
        "inverse-primary": "#b7c4ff",
        "inverse-surface": "#2e3039",
        "on-surface-variant": "#434655",
        "surface-container": "#ededf9",
        "on-tertiary-fixed-variant": "#832700",
        "outline-variant": "#c4c5d7",
        "primary-fixed-dim": "#b7c4ff",
        "on-tertiary-fixed": "#390c00",
        "tertiary-fixed-dim": "#ffb59c",
        "surface-dim": "#d9d9e5",
        "surface-container-high": "#e8e7f3",
        "on-primary-container": "#cad3ff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffc9b7",
        "on-secondary-container": "#54647a",
        "tertiary-fixed": "#ffdbcf",
        "primary-container": "#1d4ed8",
        "secondary-fixed": "#d3e4fe",
        "secondary": "#505f76",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#7f2500",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-background": "#1a1b23",
        "on-primary-fixed": "#001551",
        "primary": "#0037b0",
        "surface-container-highest": "#e2e1ed",
        "outline": "#747686",
        "surface": "#faf8ff",
        "inverse-on-surface": "#f0f0fb",
        "background": "#faf8ff",
        "tertiary-container": "#a73400",
        "on-error": "#ffffff",
        "on-surface": "#1a1b23",
        "on-primary-fixed-variant": "#0039b5",
        "surface-tint": "#2151da",
        "surface-container-low": "#f3f2fe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "card-padding": "16px",
        "section-gap": "32px",
        "page-padding": "24px",
        "stack-gap": "8px",
        "element-gap": "12px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
